apiVersion: v1
kind: Namespace
metadata:
  name: ems

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: ems
  name: ems-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: ems-service
              servicePort: 8080

---

apiVersion: v1
kind: Service
metadata:
  namespace: ems
  name: ems-service
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  selector:
    app: ems
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP

---

apiVersion: v1
kind: Pod
metadata:
  namespace: ems
  name: ems-pod
  labels:
    app: ems
spec:
  containers:
    - name: database
      image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: 'root'
        - name: MYSQL_DATABASE
          value: 'ems'
    - name: server
      image: ems
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
      env:
        - name: MYSQL_USERNAME
          value: 'root'
        - name: MYSQL_PASSWORD
          value: 'root'
        - name: MYSQL_DATABASE
          value: 'ems'
        - name: PROFILE
          value: 'production'

